### ISSUE TITLE
Non-regular files should be skipped

### ISSUE THREAD

**Issue by jedisct1** [tux3/tbak#2]
Directories such as `/tmp` or `/var` can have files such as sockets, pipes and devices.

They currently cause tbak to abort:

```
Uploading tmux-0/default...
terminate called after throwing an instance of 'std::runtime_error'
  what():  File::readAll: Unabled to open /tmp/tmux-0/default
Aborted
```

Maybe these files should be ignored instead of aborting the whole process.

**Comment by tux3** [comment]
Can you test with this new patch ?

NOTE: You will need to run "folder update" to re-generate the list of tracked files first.

**Comment by tux3** [comment]
Fixed.
